import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { BookOpen, Brain, Video, Sparkles } from 'lucide-react'
import { TopNav } from '@/components/TopNavBar'

export default function LandingPage() {
	return (
		<div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
			<TopNav variant="landing" />

			{/* Hero Section */}
			<section className="container mx-auto px-4 py-20 md:py-32">
				<div className="max-w-4xl mx-auto text-center space-y-8">
					<div className="inline-flex items-center gap-2 bg-indigo-100 text-indigo-700 px-4 py-2 rounded-full text-sm font-medium">
						<Sparkles className="h-4 w-4" />
						AI-Powered Learning
					</div>

					<h1 className="text-5xl md:text-7xl font-bold text-balance leading-tight">
						Study Smarter with{' '}
						<span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600">
							AI Video Lessons
						</span>
					</h1>

					<p className="text-xl md:text-2xl text-gray-600 text-balance leading-relaxed max-w-2xl mx-auto">
						Get personalized study videos generated by AI, narrated by your favorite Family Guy characters.
						Learn any subject in bite-sized, engaging content.
					</p>

					<div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
						<Link href="/login">
							<Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-6 text-lg">
								Get Started Free
							</Button>
						</Link>
						<Button size="lg" variant="outline" className="border-indigo-200 text-indigo-700 hover:bg-indigo-50 px-8 py-6 text-lg">
							Watch Demo
						</Button>
					</div>
				</div>
			</section>

			{/* Features Section */}
			<section className="container mx-auto px-4 py-20">
				<div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
					<div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 space-y-4">
						<div className="h-12 w-12 bg-indigo-100 rounded-xl flex items-center justify-center">
							<Brain className="h-6 w-6 text-indigo-600" />
						</div>
						<h3 className="text-xl font-bold text-gray-900">AI-Generated Content</h3>
						<p className="text-gray-600 leading-relaxed">
							Our AI creates custom study videos tailored to your topic, making complex subjects easy to understand.
						</p>
					</div>

					<div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 space-y-4">
						<div className="h-12 w-12 bg-purple-100 rounded-xl flex items-center justify-center">
							<Video className="h-6 w-6 text-purple-600" />
						</div>
						<h3 className="text-xl font-bold text-gray-900">Short-Form Videos</h3>
						<p className="text-gray-600 leading-relaxed">
							TikTok-style vertical videos keep you engaged while you learn. Perfect for quick study sessions.
						</p>
					</div>

					<div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 space-y-4">
						<div className="h-12 w-12 bg-indigo-100 rounded-xl flex items-center justify-center">
							<BookOpen className="h-6 w-6 text-indigo-600" />
						</div>
						<h3 className="text-xl font-bold text-gray-900">Any Subject</h3>
						<p className="text-gray-600 leading-relaxed">
							From math to history, science to language arts - generate study videos on any topic you need.
						</p>
					</div>
				</div>
			</section>

			{/* CTA Section */}
			<section className="container mx-auto px-4 py-20">
				<div className="max-w-4xl mx-auto bg-gradient-to-r from-indigo-600 to-purple-600 rounded-3xl p-12 text-center text-white space-y-6">
					<h2 className="text-4xl md:text-5xl font-bold text-balance">
						Ready to Transform Your Study Routine?
					</h2>
					<p className="text-xl text-indigo-100 text-balance">
						Join thousands of students already learning smarter with AI-powered video lessons.
					</p>
					<Link href="/login">
						<Button size="lg" className="bg-white text-indigo-600 hover:bg-indigo-50 px-8 py-6 text-lg">
							Start Learning Now
						</Button>
					</Link>
				</div>
			</section>

			{/* Footer */}
			<footer className="border-t bg-white">
				<div className="container mx-auto px-4 py-8">
					<div className="flex flex-col md:flex-row items-center justify-between gap-4">
						<div className="flex items-center gap-2">
							<Video className="h-6 w-6 text-indigo-600" />
							<span className="text-lg font-bold text-indigo-600">EduRot</span>
						</div>
						<p className="text-gray-600 text-sm">
							© 2025 EduRot. AI-powered learning for everyone.
						</p>
					</div>
				</div>
			</footer>
		</div>
	)
}
